# Generated by Django 4.1.4 on 2022-12-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='updated_on',
            new_name='modified_on',
        ),
    ]
