# Generated by Django 4.1.4 on 2022-12-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_updated_on_product_modified_on_variation'),
        ('cart', '0002_rename_updated_on_cartitem_modified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(to='core.variation'),
        ),
    ]
