# Generated by Django 4.1.4 on 2022-12-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_updated_on_product_modified_on_variation'),
        ('cart', '0003_cartitem_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='core.variation'),
        ),
    ]
